version: '3'

services:
  web:
    image: php:8-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=technical_assignment
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=technical_assignment
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./database:/docker-entrypoint-initdb.d
